name: botambe
description: "A new Flutter project for a gamified habit tracker."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animated_text_kit: ^4.2.3 # Library for animated text effects
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1 # Swiper for card-based UI navigation
  cupertino_icons: ^1.0.8 # Cupertino-style icons for iOS-themed apps
  floor: ^1.5.0 # SQLite persistence layer for Flutter
  flutter:
    sdk: flutter # Core Flutter SDK
  flutter_bloc: ^8.1.6 # State management using the BLoC pattern
  flutter_localizations:
    sdk: flutter # Flutter internationalization support
  freezed_annotation: ^2.4.4 # Annotations for code generation with Freezed
  get_it: ^8.0.2 # Dependency injection container
  injectable: ^2.5.0 # Code generator for dependency injection
  intl: ^0.19.0 # Internationalization and localization utilities
  json_annotation: ^4.9.0 # Annotations for JSON serialization/deserialization
  loading_indicator: ^3.1.1 # Collection of customizable loading animations
  path: ^1.9.0 # Utilities for handling file system paths
  path_provider: ^2.1.5 # Access to commonly used locations on the filesystem
  shared_preferences: ^2.3.3 # Local key-value storage for simple data persistence
  sqflite: ^2.4.1 # SQLite plugin for Flutter
  styled_widget: ^0.4.1 # Functional and declarative UI styling for Flutter
  supabase_auth_ui: ^0.5.4 # Prebuilt authentication UI for Supabase
  supabase_flutter: ^2.8.3  # Supabase SDK for Flutter
  textstyle_extensions: ^2.0.0-nullsafety # Utility for extending text styles

dev_dependencies:
  build_runner: ^2.4.13 # Tool for generating code
  floor_generator: ^1.5.0 # Code generator for Floor ORM
  flutter_lints: ^5.0.0 # Recommended lint rules for Flutter
  flutter_test:
    sdk: flutter # Testing framework for Flutter apps
  freezed: ^2.5.7 # Code generator for Freezed data classes
  injectable_generator: ^2.6.2 # Code generator for Injectable DI
  json_serializable: ^6.8.0 # Code generator for JSON serialization

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
